# SET PRODUCTION VALUES
version: '2.3'

services:
  demo.willopez.com:
    environment:
      LETSENCRYPT_HOST: demo.willopez.com,www.demo.willopez.com
      LETSENCRYPT_EMAIL: will@willopez.com
  admindemo.willopez.com:
    environment:
      DB_NAME: prod_wp
      DB_USER: prod_wp
      DB_PASSWORD: prod_wp
      WP_REDIS_HOST: wp-redis
      WP_CACHE_KEY_SALT: admindemo.willopez.com
      LETSENCRYPT_HOST: admindemo.willopez.com
      LETSENCRYPT_EMAIL: will@willopez.com
  db.demo.willopez.com:
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: prod_wp
      MYSQL_USER: prod_wp
      MYSQL_PASSWORD: prod_wp